"""Initial migration

Revision ID: af3cc9b0c364
Revises: 
Create Date: 2023-04-27 23:20:03.860576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3cc9b0c364'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=280), nullable=False),
    sa.Column('description', sa.String(length=280), nullable=False),
    sa.Column('location', sa.String(length=280), nullable=False),
    sa.Column('city', sa.String(length=280), nullable=False),
    sa.Column('date', sa.String(length=280), nullable=False),
    sa.Column('numPlayers', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('ongoing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_model')
    op.drop_table('match_model')
    # ### end Alembic commands ###
